version: 0.2

env:
  variables:
    AWS_REGION_NAME: ap-northeast-2
    ECR_REPOSITORY_NAME: sbcntr-backend
    ECS_CONTAINER_NAME: app
    DOCKER_BUILDKIT: "1"

phases:
  pre_build:
    commands:
      - echo "===== Pre Build Start ====="
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_NAME}.amazonaws.com/${ECR_REPOSITORY_NAME}
      - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c 1-7)

      - echo "AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}"
      - echo "REPOSITORY_URI=${REPOSITORY_URI}"
      - echo "IMAGE_TAG=${IMAGE_TAG}"

      - echo "===== Login to Amazon ECR ====="
      - aws ecr --region ${AWS_REGION_NAME} get-login-password | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_NAME}.amazonaws.com

  build:
    commands:
      - echo "===== Docker Build Start ====="
      - docker image build -t ${REPOSITORY_URI}:${IMAGE_TAG} .

  post_build:
    commands:
      - echo "===== Docker Push Start ====="
      - docker image push ${REPOSITORY_URI}:${IMAGE_TAG}

      - echo "===== Create imagedefinitions.json ====="
      - printf '[{"name":"%s","imageUri":"%s"}]' "${ECS_CONTAINER_NAME}" "${REPOSITORY_URI}:${IMAGE_TAG}" > imagedefinitions.json

      - echo "===== Check imagedefinitions.json ====="
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
